select * from customer limit 20

--Q1.What is the total Revenue generated by male vs Female customers?
select gender, SUM (purchase_amount) as Revenue
from customer 
group by gender 

--Q2.Which customer used a discount but still spent more that the average purchase amount?
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3. Which are the Top five Products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer  
group by item_purchased 
order by  AVG(review_rating) desc
limit 5;

--Q4.Compare the Average purchase amounts between Standard and Express Shiping
select shipping_type, ROUND(AVG(purchase_amount),2) as Amount 
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5.Do Subscribed customers spend more ? 
--Compare average spend and total revenue between subscribers and non-subscribers
select subscription_status, COUNT(customer_id) as Total_Customer,
ROUND(AVG(purchase_amount),2) as Average_Spend,
ROUND(SUM(purchase_amount),2) as Total_Revenue 
from customer 
group by subscription_status 
order by Total_Revenue desc

--Q6.Which 5 Products have the Highest percentage of purchase with discounts applied?
select item_purchased, 
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;	

--Q7.Segment customers into New, Returning, and Loyal based on their total number of previous
--purchases, and show the count of each segment 
with customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
	ELSE 'Loyal'
	END as Customer_Segment
from customer
)

select Customer_Segment, COUNT(*) as "No.of.Customers"
from customer_type 
group by Customer_Segment 

--Q8.What are the 3 Top most purchased products within each Category ?
with item_counts as (
select category, item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3 ;

--Q9.Are Customers who are repeat buyers(more than 5 previous pruchases) also likely to subscribe?
select subscription_status,
COUNT(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5
group by subscription_status

--Q10.What is the Revenue Contribution of each age group ?
select age_group,
SUM(purchase_amount) as Total_Revenue
from customer
group by age_group
order by Total_Revenue DESC;
